#!/usr/bin/env php
<?php
/**
 * alphavel CLI - Artisan-like Console
 * 
 * Usage:
 *   ./alphavel list
 *   ./alphavel make:controller UserController
 *   ./alphavel make:model User
 *   ./alphavel cache:clear
 *   ./alphavel serve
 */

require __DIR__ . '/vendor/autoload.php';

use Alphavel\Framework\Console\Console;

// Create console application
$console = new Console();
$console->setName('alphavel');
$console->setVersion('1.0.0');

// Auto-discover commands from core
$console->autodiscover(__DIR__ . '/packages/core/src/Console/Commands');

// Auto-discover user commands (if directory exists)
$console->autodiscover(__DIR__ . '/app/Console/Commands');

// Run console
exit($console->run($argv));
